
export const missionToBlockMap: Record<string, string> = {
    'Hora de acordar': 'Hora de Acordar',
    'Arrumar a cama': 'Hora de Acordar',
    'Tomar café da manhã': 'Hora de Acordar',
    'Escovar os dentes (após acordar)': 'Hora de Acordar',
    'Sair para escola': 'Saindo para escola',
    'Entrada na escola': 'Hora da Escola',
    'Saída da escola': 'Hora da Escola',
    'Tomar banho pela Manhã': 'Hora do Almoço',
    'Almoçar': 'Hora do Almoço',
    'Escovar os dentes (após almoço)': 'Hora do Almoço',
    'Fazer a lição de casa': 'Tarefas Escolares',
    'Organizar a mochila para escola': 'Tarefas Escolares',
    'Lanche da tarde': 'Lanche da tarde',
    'Hora do Jantar': 'Hora do Jantar',
    'Escovar os dentes (após jantar)': 'Hora do Jantar',
    'Tomar banho a Noite': 'Hora de Dormir',
    'Tomar banho a tarde': 'Hora de Dormir',
    'Escovar os dentes (antes de dormir)': 'Hora de Dormir',
    'Hora de dormir': 'Hora de Dormir',
    'Hora livre para brincar': 'Atividades Extras',
};
