
import type { MissionCategory, Weekday } from '@/lib/types';
import { Home, HeartPulse, Smile, Users, Coins, Leaf, Bike, type LucideIcon, ListChecks, Palette, Languages, HandHelping, BrainCircuit, ShieldCheck, TowerControl, NotebookPen, Puzzle } from 'lucide-react';

export interface PredefinedMissionIdea {
  title: string;
  emoji: string;
  suggestedAppCategory: MissionCategory;
  starsReward: number;
  xpReward: number;
}

export interface PredefinedMissionGroup {
  userCategory: string;
  icon: LucideIcon;
  description: string;
  items: PredefinedMissionIdea[];
}

export const predefinedMissionGroups: PredefinedMissionGroup[] = [
  {
    userCategory: 'Rotinas Essencial (diárias)',
    icon: ListChecks,
    description: 'Missões essenciais que formam a espinha dorsal de um dia produtivo e saudável para qualquer Mini Herói.',
    items: [
      { title: 'Hora de acordar', emoji: '⏰', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Arrumar a cama', emoji: '🛏️', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Tomar café da manhã', emoji: '☕', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Escovar os dentes (após acordar)', emoji: '🪥', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Almoçar', emoji: '🍽️', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Escovar os dentes (após almoço)', emoji: '🪥', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Tomar banho', emoji: '🚿', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Sair para escola', emoji: '🎒', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Jantar', emoji: '🍽️', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Escovar os dentes (após jantar)', emoji: '🪥', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Hora de dormir', emoji: '😴', suggestedAppCategory: 'essential_routines', starsReward: 5, xpReward: 10 },
      { title: 'Fazer a lição de casa', emoji: '✍️', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Organizar a mochila para amanhã', emoji: '🎒', suggestedAppCategory: 'school', starsReward: 10, xpReward: 15 },
      { title: 'Hora livre para brincar', emoji: '🧩', suggestedAppCategory: 'hobbies', starsReward: 5, xpReward: 10 },
    ],
  },
  {
    userCategory: 'Terapias e Acompanhamentos de Saúde',
    icon: HeartPulse,
    description: 'Missões para acompanhar tratamentos e consultas importantes para o bem-estar e desenvolvimento do herói.',
    items: [
      { title: 'Tomar Remédio', emoji: '💊', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
      { title: 'Tomar Vacinas', emoji: '💉', suggestedAppCategory: 'health', starsReward: 20, xpReward: 30 },
      { title: 'Psicologia Infantil', emoji: '🧠', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Psicomotricidade', emoji: '🤸', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Psicopedagogia', emoji: '📝', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Terapia Ocupacional (TO)', emoji: '👐', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Fisioterapia', emoji: '💪', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Fonoaudiologia', emoji: '🗣️', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Acompanhamento Nutricional', emoji: '🥗', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Análise do Comportamento (ABA)', emoji: '🧩', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Oftalmologista', emoji: '👓', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Pediatra', emoji: '🩺', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Equoterapia', emoji: '🐎', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Integração Sensorial', emoji: '✨', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Musicoterapia', emoji: '🎵', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
      { title: 'Ir ao Dentista / Ortodontista', emoji: '🦷', suggestedAppCategory: 'health', starsReward: 15, xpReward: 25 },
    ],
  },
  {
    userCategory: 'Prática de Esportes',
    icon: Bike,
    description: 'Tarefas para motivar a prática de esportes, promovendo um estilo de vida ativo, disciplina e trabalho em equipe.',
    items: [
      { title: 'Aula de Natação', emoji: '🏊', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Futebol', emoji: '⚽', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Judô', emoji: '🥋', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Jiu-jitsu', emoji: '🥋', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Capoeira', emoji: '🤸', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Karatê', emoji: '🥋', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Andar de bicicleta', emoji: '🚴', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
      { title: 'Aula de Vôlei', emoji: '🏐', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Basquete', emoji: '🏀', suggestedAppCategory: 'sports', starsReward: 15, xpReward: 20 },
    ],
  },
  {
    userCategory: 'Prática de Artes',
    icon: Palette,
    description: 'Incentive a criatividade e a expressão artística com missões focadas em música, dança e artes visuais.',
    items: [
      { title: 'Aula de Dança', emoji: '💃', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Balé', emoji: '🩰', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Piano/Teclado', emoji: '🎹', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Violão', emoji: '🎸', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Guitarra', emoji: '🎸', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Bateria', emoji: '🥁', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Canto', emoji: '🎤', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Desenho', emoji: '✏️', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Pintura', emoji: '🎨', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Aula de Teatro', emoji: '🎭', suggestedAppCategory: 'hobbies', starsReward: 15, xpReward: 20 },
      { title: 'Tocar um instrumento por 15 min', emoji: '🎶', suggestedAppCategory: 'hobbies', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Prática de Idiomas',
    icon: Languages,
    description: 'Missões para incentivar o aprendizado e a prática de novas línguas, abrindo as portas para novas culturas.',
    items: [
      { title: 'Aula de Inglês', emoji: '🇬🇧', suggestedAppCategory: 'languages', starsReward: 15, xpReward: 25 },
      { title: 'Aula de Espanhol', emoji: '🇪🇸', suggestedAppCategory: 'languages', starsReward: 15, xpReward: 25 },
      { title: 'Aula de Francês', emoji: '🇫🇷', suggestedAppCategory: 'languages', starsReward: 15, xpReward: 25 },
      { title: 'Aula de Alemão', emoji: '🇩🇪', suggestedAppCategory: 'languages', starsReward: 15, xpReward: 25 },
      { title: 'Aula de Italiano', emoji: '🇮🇹', suggestedAppCategory: 'languages', starsReward: 15, xpReward: 25 },
      { title: 'Praticar com app de idiomas', emoji: '📱', suggestedAppCategory: 'languages', starsReward: 10, xpReward: 15 },
      { title: 'Assistir a um desenho no novo idioma', emoji: '📺', suggestedAppCategory: 'languages', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Atividades da Escola',
    icon: NotebookPen,
    description: 'Tarefas que ajudam a criar e manter uma rotina de estudos sólida e a desenvolver a responsabilidade acadêmica.',
    items: [
      { title: 'Ler por 20 minutos', emoji: '📖', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Estudar para uma prova', emoji: '📝', suggestedAppCategory: 'school', starsReward: 20, xpReward: 30 },
      { title: 'Revisar o conteúdo do dia', emoji: '🧐', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Praticar matemática/tabuada', emoji: '➕', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Avançar no trabalho escolar', emoji: '💻', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Preparar o estojo para a semana', emoji: '✏️', suggestedAppCategory: 'school', starsReward: 10, xpReward: 15 },
      { title: 'Manter cadernos organizados', emoji: '📓', suggestedAppCategory: 'school', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Ajudar em Casa',
    icon: Home,
    description: 'Tarefas focadas na responsabilidade com o lar e o ambiente compartilhado, incentivando a colaboração e a organização.',
    items: [
      { title: 'Guardar os brinquedos após o uso', emoji: '🧸', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Levar o prato para a pia', emoji: '🍽️', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Ajudar a pôr a mesa', emoji: '🍽️', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Ajudar a tirar a mesa', emoji: '🧼', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Cuidar do pet (comida e água)', emoji: '🐾', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Regar as plantas', emoji: '🌱', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Guardar sapatos e casacos', emoji: '👟', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Ajudar a guardar as compras', emoji: '🛒', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Manter a escrivaninha organizada', emoji: '📚', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Ajudar a dobrar roupas limpas', emoji: '👕', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Guardar as próprias roupas', emoji: '👕', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Deixar a toalha de banho estendida', emoji: '🛁', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Levar o lixo para a lixeira principal', emoji: '🗑️', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Comportamental',
    icon: Smile,
    description: 'Tarefas que incentivam o desenvolvimento de habilidades socioemocionais, como paciência, empatia, respeito e inteligência emocional.',
    items: [
      { title: 'Usar "por favor" e "obrigado"', emoji: '🙏', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Resolver um conflito com diálogo', emoji: '💬', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Esperar a sua vez de falar', emoji: '🤐', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Expressar sentimentos com palavras', emoji: '❤️', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Cuidar bem dos seus pertences', emoji: '✨', suggestedAppCategory: 'behavior', starsReward: 15, xpReward: 20 },
      { title: 'Aceitar um "não" sem birra', emoji: '😊', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Manter a calma ao se frustrar', emoji: '😌', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Não interromper os outros', emoji: '🤫', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Pedir desculpas quando errar', emoji: '😔', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Falar com um tom de voz calmo', emoji: '🗣️', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Ter paciência em filas/esperas', emoji: '⏳', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Olhar nos olhos ao conversar', emoji: '👀', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Respeitar as regras de um jogo', emoji: '🎲', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Cumprimentar ao chegar e sair', emoji: '👋', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
      { title: 'Demonstrar boa postura na mesa', emoji: '🧘', suggestedAppCategory: 'behavior', starsReward: 15, xpReward: 20 },
      { title: 'Ser honesto sobre um erro', emoji: '🙋', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
    ],
  },
  {
    userCategory: 'Saúde e Bem-Estar',
    icon: HeartPulse,
    description: 'Missões focadas no autocuidado, higiene, alimentação e na construção de um estilo de vida saudável para o corpo e a mente.',
    items: [
        { title: 'Beber bastante água', emoji: '💧', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Fazer 30 min de atividade física', emoji: '💪', suggestedAppCategory: 'health', starsReward: 15, xpReward: 20 },
        { title: 'Fazer um alongamento rápido', emoji: '🤸', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Comer uma fruta no lanche', emoji: '🍎', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Experimentar um vegetal novo', emoji: '🥦', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Fazer uma pausa das telas', emoji: '📵', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Lavar as mãos antes de comer', emoji: '🙌', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Ajudar a preparar um lanche saudável', emoji: '🥗', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Passar protetor solar', emoji: '☀️', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Praticar 5 min de respiração/calma', emoji: '🧘', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Lavar o rosto ao acordar e dormir', emoji: '🧼', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Usar o fio dental', emoji: '🦷', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
    ],
  },
  {
    userCategory: 'Social',
    icon: Users,
    description: 'Focadas na interação e no fortalecimento de laços com a família e amigos.',
    items: [
        { title: 'Ligar para os avós para conversar', emoji: '📞', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Organizar noite de jogos em família', emoji: '🎲', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Fazer um desenho para a família', emoji: '🎨', suggestedAppCategory: 'social', starsReward: 10, xpReward: 15 },
        { title: 'Participar de atividade em grupo', emoji: '👨‍👩‍👧‍👦', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Compartilhar um brinquedo', emoji: '🤗', suggestedAppCategory: 'social', starsReward: 10, xpReward: 15 },
        { title: 'Perguntar como foi o dia da família', emoji: '🤔', suggestedAppCategory: 'social', starsReward: 10, xpReward: 15 },
        { title: 'Fazer refeições em família, sem telas', emoji: '🍽️', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Contar uma história para o irmão', emoji: '📖', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Elogiar a conquista de um amigo', emoji: '🎉', suggestedAppCategory: 'social', starsReward: 15, xpReward: 20 },
        { title: 'Defender um colega de injustiça', emoji: '🛡️', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
    ],
  },
  {
    userCategory: 'Financeiro',
    icon: Coins,
    description: 'Pequenas missões para introduzir conceitos de educação financeira de forma simples, prática e lúdica.',
    items: [
        { title: 'Guardar dinheiro no cofrinho', emoji: '🐖', suggestedAppCategory: 'financial', starsReward: 10, xpReward: 15 },
        { title: 'Ajudar na lista de compras', emoji: '📝', suggestedAppCategory: 'financial', starsReward: 10, xpReward: 15 },
        { title: 'Cuidar da própria mesada', emoji: '💰', suggestedAppCategory: 'financial', starsReward: 10, xpReward: 15 },
        { title: 'Criar uma "lista de desejos"', emoji: '⭐', suggestedAppCategory: 'financial', starsReward: 10, xpReward: 15 },
        { title: 'Diferenciar "necessidade" e "desejo"', emoji: '⚖️', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 20 },
        { title: 'Não pedir coisas fora do planejado', emoji: '🙅', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 20 },
        { title: 'Ajudar a planejar o orçamento de um passeio', emoji: '🗺️', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 20 },
        { title: 'Não gastar toda a mesada de uma vez', emoji: '🏦', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 20 },
        { title: 'Poupar parte do dinheiro que ganhar', emoji: '📊', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 20 },
    ],
  },
  {
    userCategory: 'Ambiental',
    icon: Leaf,
    description: 'Tarefas que promovem a consciência ecológica, o respeito pela natureza e o cuidado com o planeta.',
    items: [
        { title: 'Apagar as luzes ao sair do cômodo', emoji: '💡', suggestedAppCategory: 'environmental', starsReward: 5, xpReward: 10 },
        { title: 'Fechar a torneira ao escovar os dentes', emoji: '💧', suggestedAppCategory: 'environmental', starsReward: 5, xpReward: 10 },
        { title: 'Separar o lixo para reciclagem', emoji: '♻️', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Cuidar de uma planta ou horta', emoji: '🌱', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Criar um brinquedo com recicláveis', emoji: '🤖', suggestedAppCategory: 'environmental', starsReward: 15, xpReward: 20 },
        { title: 'Não deixar lixo em parques/praias', emoji: '🗑️', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Não desperdiçar comida', emoji: '🍽️', suggestedAppCategory: 'environmental', starsReward: 15, xpReward: 20 },
        { title: 'Usar os dois lados de uma folha', emoji: '📄', suggestedAppCategory: 'environmental', starsReward: 5, xpReward: 10 },
    ],
  },
];

export const weekdayLabels: Record<Weekday, { long: string, short: string }> = {
  SU: { long: 'Domingo', short: 'Dom' },
  MO: { long: 'Segunda-feira', short: 'Seg' },
  TU: { long: 'Terça-feira', short: 'Ter' },
  WE: { long: 'Quarta-feira', short: 'Qua' },
  TH: { long: 'Quinta-feira', short: 'Qui' },
  FR: { long: 'Sexta-feira', short: 'Sex' },
  SA: { long: 'Sábado', short: 'Sáb' },
};
