
import type { RewardCategory } from '@/lib/types';
import { Crown, PartyPopper, ShoppingBag, GraduationCap, HeartHandshake, type LucideIcon } from 'lucide-react';

export interface PredefinedRewardIdea {
  title: string;
  description?: string;
  userCategory: string; // A categoria principal do usuário (ex: "Privilégios")
  userSubCategory?: string; // A subcategoria do usuário (ex: "Controle")
  suggestedAppCategory: RewardCategory; // A categoria correspondente do app
  isMaterialSuggestion?: boolean; // Se a sugestão tende a ser material
  // suggestedStarsCost?: number; // Opcional: custo sugerido
}

export interface PredefinedRewardGroup {
  userCategory: string;
  icon: LucideIcon;
  items: PredefinedRewardIdea[];
}

export const predefinedRewardGroups: PredefinedRewardGroup[] = [
  {
    userCategory: "Privilégios",
    icon: Crown,
    items: [
      {
        title: "Escolher o filme da família",
        description: "A criança escolhe o filme que a família assistirá na noite de cinema.",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "DJ Oficial da Viagem",
        description: "Escolher a playlist de músicas durante uma viagem de carro.",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Chef da Noite Auxiliar",
        description: "Ajudar a escolher o cardápio do jantar (entre opções pré-definidas).",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Decidir a Atividade do Fim de Semana",
        description: "Decidir qual jogo de tabuleiro ou atividade em família será feito.",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Fotógrafo da Família por um Dia",
        description: "Usar o celular de um dos pais (com supervisão) para registrar momentos.",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Planejar Café da Manhã Especial",
        description: "Planejar o menu do café da manhã especial de sábado.",
        userCategory: "Privilégios",
        userSubCategory: "Controle",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "30 Minutos Extras de Tela",
        description: "Tempo extra de videogame, tablet ou TV.",
        userCategory: "Privilégios",
        userSubCategory: "Flexibilidade",
        suggestedAppCategory: "extra-time",
        isMaterialSuggestion: false,
      },
      {
        title: "Dormir 30 Minutos Mais Tarde",
        description: "Em um dia de fim de semana, dormir um pouco depois do horário habitual.",
        userCategory: "Privilégios",
        userSubCategory: "Flexibilidade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Vale-Pular-Tarefa",
        description: "Direito a pular uma tarefa doméstica de baixo impacto por um dia.",
        userCategory: "Privilégios",
        userSubCategory: "Flexibilidade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "15 Minutos Livres Extras",
        description: "Ter 15 minutos de 'tempo livre' extra antes de começar a lição de casa.",
        userCategory: "Privilégios",
        userSubCategory: "Flexibilidade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Dia da Roupa Especial",
        description: "Escolher usar uma roupa 'especial' (fantasia, capa) em um dia normal em casa.",
        userCategory: "Privilégios",
        userSubCategory: "Flexibilidade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Encontro Exclusivo 1-para-1",
        description: "Um 'encontro exclusivo' com o pai ou a mãe para uma atividade especial.",
        userCategory: "Privilégios",
        userSubCategory: "Exclusividade",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Dia do Sim (com Regras)",
        description: "Dentro de regras pré-definidas, os pais dizem 'sim' aos pedidos por um período.",
        userCategory: "Privilégios",
        userSubCategory: "Exclusividade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Contar a Primeira História",
        description: "Direito a contar a primeira história na hora de dormir.",
        userCategory: "Privilégios",
        userSubCategory: "Exclusividade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
      {
        title: "Café da Manhã na Cama",
        description: "Ter um café da manhã ou lanche especial servido na cama.",
        userCategory: "Privilégios",
        userSubCategory: "Exclusividade",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Ser o Primeiro a Experimentar Algo Novo",
        description: "Ser o primeiro a experimentar algo novo que a família comprou.",
        userCategory: "Privilégios",
        userSubCategory: "Exclusividade",
        suggestedAppCategory: "privilege",
        isMaterialSuggestion: false,
      },
    ],
  },
  {
    userCategory: "Experiências",
    icon: PartyPopper,
    items: [
      {
        title: "Piquenique Temático",
        description: "Piquenique no parque ou na praia com um tema divertido.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Acampamento na Sala",
        description: "Acampamento na sala de estar, com cabana de lençóis e lanternas.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Caça ao Tesouro em Casa",
        description: "Caça ao tesouro com pistas e um pequeno prêmio no final.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Noite de Culinária Divertida",
        description: "Fazer pizzas, cookies ou um bolo divertido em família.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Sessão de Fotos Temáticas",
        description: "Sessão de fotos em casa, com fantasias e cenários improvisados.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Cápsula do Tempo Familiar",
        description: "Fazer uma 'cápsula do tempo' em família para ser aberta no futuro.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Noite de Karaokê em Família",
        description: "Noite de Karaokê com as músicas favoritas de todos.",
        userCategory: "Experiências",
        userSubCategory: "Em Família",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Festa do Pijama com Amigos",
        description: "Convidar um ou dois amigos para uma festa do pijama.",
        userCategory: "Experiências",
        userSubCategory: "Social",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Levar Amigo para Passeio",
        description: "Direito de levar um amigo para um passeio em família (cinema, parque).",
        userCategory: "Experiências",
        userSubCategory: "Social",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Olimpíada no Quintal",
        description: "Organizar uma pequena 'olimpíada' no quintal ou parque com os amigos.",
        userCategory: "Experiências",
        userSubCategory: "Social",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Chamada de Vídeo Estendida",
        description: "Uma chamada de vídeo mais longa com um primo ou amigo que mora longe.",
        userCategory: "Experiências",
        userSubCategory: "Social",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Passeio Cultural Interativo",
        description: "Passeio a um museu interativo, zoológico ou planetário.",
        userCategory: "Experiências",
        userSubCategory: "Cultural",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Estreia no Cinema",
        description: "Ir ao cinema para assistir a um filme de estreia.",
        userCategory: "Experiências",
        userSubCategory: "Cultural",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Visita a Jardim Botânico ou Feira",
        description: "Visitar um jardim botânico ou uma feira de ciências.",
        userCategory: "Experiências",
        userSubCategory: "Cultural",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Peça de Teatro Infantil",
        description: "Ir a uma peça de teatro infantil.",
        userCategory: "Experiências",
        userSubCategory: "Cultural",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
    ],
  },
  {
    userCategory: "Itens Materiais (com Propósito)",
    icon: ShoppingBag,
    items: [
      {
        title: "Livro Novo Escolhido",
        description: "Um livro novo escolhido pela criança na livraria.",
        userCategory: "Itens Materiais",
        userSubCategory: "Relacionados a Hobbies",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Kit de Arte Específico",
        description: "Um kit de arte ou material específico (aquarelas, argila, canetas especiais).",
        userCategory: "Itens Materiais",
        userSubCategory: "Relacionados a Hobbies",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Acessório para Esporte",
        description: "Um acessório para um esporte que pratica (meião de futebol, munhequeira).",
        userCategory: "Itens Materiais",
        userSubCategory: "Relacionados a Hobbies",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Partitura Nova",
        description: "Partitura de uma música nova para o instrumento que estuda.",
        userCategory: "Itens Materiais",
        userSubCategory: "Relacionados a Hobbies",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Adesivos Decorativos",
        description: "Adesivos novos para decorar o skate, bicicleta ou caderno.",
        userCategory: "Itens Materiais",
        userSubCategory: "Relacionados a Hobbies",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Escolher Modelo/Cor de Item Planejado",
        description: "O direito de escolher o modelo/cor de um tênis ou roupa que já seria comprado.",
        userCategory: "Itens Materiais",
        userSubCategory: "Necessidades Planejadas",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Escolher Estampa de Material Escolar",
        description: "Escolher a estampa da mochila ou do estojo para o próximo ano letivo.",
        userCategory: "Itens Materiais",
        userSubCategory: "Necessidades Planejadas",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Pacote de Figurinhas",
        description: "Pacote de figurinhas para um álbum.",
        userCategory: "Itens Materiais",
        userSubCategory: "Pequenos Mimos",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Gibi ou Revista em Quadrinhos",
        description: "Um gibi ou revista em quadrinhos.",
        userCategory: "Itens Materiais",
        userSubCategory: "Pequenos Mimos",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Chaveiro de Personagem",
        description: "Um chaveiro do seu personagem favorito.",
        userCategory: "Itens Materiais",
        userSubCategory: "Pequenos Mimos",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Massinha de Modelar Nova Cor",
        description: "Massinha de modelar de uma cor diferente.",
        userCategory: "Itens Materiais",
        userSubCategory: "Pequenos Mimos",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
    ],
  },
  {
    userCategory: "Desenvolvimento Pessoal",
    icon: GraduationCap,
    items: [
      {
        title: "Aula Experimental",
        description: "Uma aula experimental (música, esporte, programação, artes marciais).",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Aprendizado",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: false,
      },
      {
        title: "Kit de Ciências",
        description: "Um kit de ciências (química, vulcões, fósseis).",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Aprendizado",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: true,
      },
      {
        title: "Curso Online Rápido",
        description: "Inscrição em um curso online rápido sobre um tema de interesse.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Aprendizado",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: false,
      },
      {
        title: "App ou Jogo Educativo Premium",
        description: "Um aplicativo ou jogo educativo premium.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Aprendizado",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: false,
      },
      {
        title: "Assinatura de Revista Infantil Educativa",
        description: "Assinatura de uma revista infantil educativa.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Aprendizado",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: true,
      },
      {
        title: "Kit Faça Você Mesmo (DIY)",
        description: "Kit de 'faça você mesmo' (construção de robô, criação de bijuterias).",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Criatividade",
        suggestedAppCategory: "learning",
        isMaterialSuggestion: true,
      },
      {
        title: "Diário ou Caderno de Desenho de Qualidade",
        description: "Um diário ou caderno de desenho de alta qualidade.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Criatividade",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Ingressos para Oficina Criativa",
        description: "Ingressos para uma oficina de arte ou teatro.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Criatividade",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Microfone de Brinquedo",
        description: "Um microfone de brinquedo para cantar e gravar a própria voz.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Criatividade",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Dia em Parque de Aventuras",
        description: "Um dia em um parque de trampolins ou de arvorismo.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Saúde e Bem-estar",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
      {
        title: "Item para Atividade Física",
        description: "Um item que incentive atividade física (corda, bambolê, patins).",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Saúde e Bem-estar",
        suggestedAppCategory: "material",
        isMaterialSuggestion: true,
      },
      {
        title: "Dia de Spa em Casa",
        description: "Um 'dia de spa' em casa, com massagem nos pés e cuidados divertidos.",
        userCategory: "Desenvolvimento Pessoal",
        userSubCategory: "Saúde e Bem-estar",
        suggestedAppCategory: "experience",
        isMaterialSuggestion: false,
      },
    ],
  },
  {
    userCategory: "Impacto e Generosidade",
    icon: HeartHandshake,
    items: [
      {
        title: "Doar Brinquedo/Livro Novo",
        description: "Escolher um brinquedo ou livro novo para ser doado em seu nome.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Doação",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false, // A ação é doar, não receber
      },
      {
        title: "Doação Familiar para ONG",
        description: "A família faz uma doação para uma ONG escolhida pelo Mini Herói.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Doação",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Apadrinhar uma Árvore",
        description: "A família 'apadrinha' uma árvore em um projeto de reflorestamento.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Doação",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Ajudar em Abrigo de Animais",
        description: "Passar uma tarde em família ajudando em um abrigo de animais.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Voluntariado",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Mutirão de Limpeza",
        description: "Participar de um mutirão de limpeza de uma praça ou praia local.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Voluntariado",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Ajudar em Campanha de Agasalho",
        description: "Ajudar a organizar os donativos em uma campanha de agasalho.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Voluntariado",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Preparar Lanches para Doar",
        description: "Preparar e entregar lanches para pessoas em situação de rua.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Atos de Gentileza",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Desenho/Cartão para Vizinho",
        description: "Fazer um desenho ou cartão e entregar a um vizinho idoso.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Atos de Gentileza",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
      {
        title: "Comprar Flores para Presentear",
        description: "Comprar flores com os pais para dar de presente surpresa a um parente.",
        userCategory: "Impacto e Generosidade",
        userSubCategory: "Atos de Gentileza",
        suggestedAppCategory: "social-impact",
        isMaterialSuggestion: false,
      },
    ],
  },
];
