
import type { MissionCategory } from '@/lib/types';
import { Home, School, HeartPulse, Smile, Users, Banknote, Leaf, Bike, type LucideIcon } from 'lucide-react';

export interface PredefinedMissionIdea {
  title: string;
  suggestedAppCategory: MissionCategory;
  starsReward: number;
  xpReward: number;
}

export interface PredefinedMissionGroup {
  userCategory: string;
  icon: LucideIcon;
  description: string;
  items: PredefinedMissionIdea[];
}

export const predefinedMissionGroups: PredefinedMissionGroup[] = [
  {
    userCategory: 'Casa',
    icon: Home,
    description: 'Tarefas focadas na responsabilidade com o lar e o ambiente compartilhado, incentivando a colaboração e a organização.',
    items: [
      { title: 'Arrumar a cama pela manhã.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Guardar os brinquedos após o uso.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Levar o prato para a pia.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Ajudar a pôr a mesa.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Ajudar a tirar a mesa.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Cuidar do pet (comida e água).', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Regar as plantas.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Separar o lixo reciclável.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Guardar sapatos e casacos.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Ajudar a guardar as compras.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Manter a escrivaninha organizada.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Tirar o pó de um móvel.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Ajudar a dobrar roupas limpas.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Guardar as próprias roupas.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Limpar a própria sujeira pequena.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Varrer um cômodo da casa.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Deixar a toalha de banho estendida.', suggestedAppCategory: 'home', starsReward: 5, xpReward: 10 },
      { title: 'Organizar a estante de livros.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Levar o lixo para a lixeira principal.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
      { title: 'Ajudar a secar a louça.', suggestedAppCategory: 'home', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Escola',
    icon: School,
    description: 'Tarefas que ajudam a criar e manter uma rotina de estudos sólida e a desenvolver a responsabilidade acadêmica.',
    items: [
      { title: 'Fazer a lição de casa.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Organizar a mochila para amanhã.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Ler por 20 minutos.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Estudar para uma prova.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Revisar o conteúdo do dia.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Praticar matemática/tabuada.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Avançar no trabalho escolar.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Fazer um resumo da matéria.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Pesquisar sobre um tópico da aula.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Ensinar algo que aprendeu.', suggestedAppCategory: 'school', starsReward: 20, xpReward: 30 },
      { title: 'Preparar o estojo para a semana.', suggestedAppCategory: 'school', starsReward: 10, xpReward: 15 },
      { title: 'Ler em voz alta para alguém.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Praticar a escrita de um texto.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Fazer exercícios de caligrafia.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Assistir a um vídeo educativo.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Montar cronograma de estudos.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Revisar erros de provas antigas.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Anotar datas de provas e trabalhos.', suggestedAppCategory: 'school', starsReward: 15, xpReward: 25 },
      { title: 'Tirar dúvidas na aula.', suggestedAppCategory: 'school', starsReward: 20, xpReward: 30 },
      { title: 'Manter cadernos organizados.', suggestedAppCategory: 'school', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Saúde e Bem-Estar',
    icon: HeartPulse,
    description: 'Missões focadas no autocuidado, higiene, alimentação e na construção de um estilo de vida saudável para o corpo e a mente.',
    items: [
        { title: 'Escovar os dentes.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Tomar banho no horário.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Beber bastante água.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Fazer 30 min de atividade física.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Fazer um alongamento rápido.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Comer uma fruta no lanche.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Experimentar um vegetal novo.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Fazer uma pausa das telas.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Lavar as mãos antes de comer.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Ir para a cama no horário.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Pentear o cabelo.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Ajudar a preparar um lanche saudável.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Passar protetor solar.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Praticar 5 min de respiração/calma.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Lavar o rosto ao acordar e dormir.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Escolher um lanche saudável.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Fazer uma caminhada com a família.', suggestedAppCategory: 'health', starsReward: 10, xpReward: 15 },
        { title: 'Dormir a noite toda na própria cama.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Usar o fio dental.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
        { title: 'Manter as unhas limpas.', suggestedAppCategory: 'health', starsReward: 5, xpReward: 10 },
    ],
  },
  {
    userCategory: 'Esportes e Atividades Físicas',
    icon: Bike,
    description: 'Missões para incentivar a prática de esportes e atividades físicas, promovendo um estilo de vida ativo e saudável.',
    items: [
        { title: 'Aula de Natação.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Treino de Futebol.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Aula de Judô/Karatê.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Aula de Jiu-Jitsu.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Andar de bicicleta por 30 min.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Andar de patins por 30 min.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Andar de patinete por 30 min.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Aula de Basquete.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
        { title: 'Praticar a coreografia da Dança/Balé.', suggestedAppCategory: 'sports', starsReward: 10, xpReward: 15 },
    ],
  },
  {
    userCategory: 'Comportamento',
    icon: Smile,
    description: 'Tarefas que incentivam o desenvolvimento de habilidades socioemocionais, como paciência, empatia, respeito e inteligência emocional.',
    items: [
        { title: 'Ajudar um irmão mais novo.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Usar "por favor" e "obrigado".', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Resolver um conflito com diálogo.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Esperar a sua vez de falar.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Expressar sentimentos com palavras.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Cuidar bem dos seus pertences.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Aceitar um "não" sem birra.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Manter a calma ao se frustrar.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Não interromper os outros.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Fazer um elogio a cada familiar.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Pedir desculpas quando errar.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Dividir o lanche ou brinquedo.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Falar com um tom de voz calmo.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Guardar um segredo confiado.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Ter paciência em filas/esperas.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Reagir bem a críticas construtivas.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Olhar nos olhos ao conversar.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Respeitar as regras de um jogo.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Deixar o outro escolher primeiro.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
        { title: 'Cumprimentar ao chegar e sair.', suggestedAppCategory: 'behavior', starsReward: 20, xpReward: 30 },
    ],
  },
  {
    userCategory: 'Social',
    icon: Users,
    description: 'Focadas na interação e no fortalecimento de laços com a família e amigos.',
    items: [
        { title: 'Ligar para os avós para conversar.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Organizar noite de jogos em família.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Fazer um desenho para a família.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Participar de atividade em grupo.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Compartilhar um brinquedo.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Perguntar como foi o dia da família.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Sugerir uma atividade em família.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Jogar sem reclamar do resultado.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Enviar um vídeo/áudio para parente.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Ajudar a arrumar a casa para visitas.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Dar um abraço em cada familiar.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Deixar um bilhete de "bom dia".', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Combinar de brincar com um amigo.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Convidar um colega novo para brincar.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Fazer refeições em família, sem telas.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Participar da conversa no jantar.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Contar história para o irmão.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Elogiar a conquista de um amigo.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Defender um colega de injustiça.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
        { title: 'Lembrar do aniversário de alguém.', suggestedAppCategory: 'social', starsReward: 20, xpReward: 30 },
    ],
  },
  {
    userCategory: 'Financeiro',
    icon: Banknote,
    description: 'Pequenas missões para introduzir conceitos de educação financeira de forma simples, prática e lúdica.',
    items: [
        { title: 'Guardar dinheiro no cofrinho.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Ajudar na lista de compras.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Pesquisar o preço de um item.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Cuidar da própria mesada.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Criar uma "lista de desejos".', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Separar moedas por valor.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Ajudar a conferir o troco.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Definir uma meta para economizar.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Criar um "pote dos sonhos".', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Não pedir coisas fora do planejado.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Ajudar a encontrar cupons.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Diferenciar "necessidade" e "desejo".', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Cuidar de um "empréstimo" simbólico.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Aprender sobre impostos em compras.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Vender um brinquedo antigo para comprar um novo.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Criar um "pequeno negócio".', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Pesquisar o preço de um ingrediente.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Ajudar a planejar o orçamento de um passeio.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Não gastar toda a mesada de uma vez.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
        { title: 'Poupar 10% do dinheiro que ganhar.', suggestedAppCategory: 'financial', starsReward: 15, xpReward: 25 },
    ],
  },
  {
    userCategory: 'Ambiental',
    icon: Leaf,
    description: 'Tarefas que promovem a consciência ecológica, o respeito pela natureza e o cuidado com o planeta.',
    items: [
        { title: 'Apagar as luzes ao sair do cômodo.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Fechar a torneira ao escovar os dentes.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Separar o lixo para reciclagem.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Cuidar de uma planta ou horta.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Criar um brinquedo com recicláveis.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Juntar água da chuva para as plantas.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Fazer um brinquedo com sucata.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Ajudar na composteira doméstica.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Limpar embalagens para reciclar.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Aprender sobre um animal em extinção.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Desenhar sobre proteger a natureza.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Desligar aparelhos da tomada.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Ir a pé ou de bicicleta em vez de carro.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Não deixar lixo em parques/praias.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Fazer um cartaz sobre economia de água.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Identificar 3 árvores perto de casa.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Montar um bebedouro para pássaros.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Não desperdiçar comida.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Usar os dois lados de uma folha.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
        { title: 'Participar de um mutirão de limpeza.', suggestedAppCategory: 'environmental', starsReward: 10, xpReward: 15 },
    ],
  },
];

    