
import type { RewardCategory } from '@/lib/types';
import { Crown, PartyPopper, ShoppingBag, GraduationCap, HeartHandshake, type LucideIcon, CakeSlice, Utensils, FerrisWheel, Plane } from 'lucide-react';

export interface PredefinedRewardIdea {
  title: string;
  description?: string;
  userCategory: string;
  suggestedAppCategory: RewardCategory;
  isMaterialSuggestion?: boolean;
  starsCost?: number;
  justification?: string;
  tip?: string;
  source: 'predefined' | 'custom';
}

export interface PredefinedRewardGroup {
  userCategory: string;
  description: string;
  icon: LucideIcon;
  items: PredefinedRewardIdea[];
}

export const predefinedRewardGroups: PredefinedRewardGroup[] = [
  {
    userCategory: "Privilégios",
    description: "Recompensas que dão à criança um senso de autonomia, controle e confiança, ensinando sobre tomada de decisão e responsabilidade de uma forma leve e divertida.",
    icon: Crown,
    items: [
      {
        title: "Ser o primeiro a experimentar algo novo",
        description: "O poder de ser o explorador oficial da família e provar um lanche ou usar algo antes de todo mundo!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 100,
        justification: "Conquista de 1 dia. Um privilégio rápido para celebrar a curiosidade.",
        tip: "Complete as missões de hoje e você ganha o poder de ser o explorador oficial da família!",
        source: 'predefined',
      },
      {
        title: "Direito a contar a primeira história",
        description: "Use sua imaginação para ser o contador de histórias oficial na hora de dormir. A primeira aventura da noite é sua!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 100,
        justification: "Conquista de 1 dia. Valoriza a criatividade e a expressão.",
        tip: "Com as estrelas de um dia de missões, você se torna o contador de histórias oficial da noite!",
        source: 'predefined',
      },
      {
        title: "Fotógrafo da Família por um Dia",
        description: "Capture os momentos mágicos! Você fica no comando da câmera para registrar as memórias do dia.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 150,
        justification: "Gratificação de 1-2 dias. Um prêmio divertido que incentiva um olhar criativo.",
        tip: "Com as estrelas de um dia e meio de missões, você vira o fotógrafo oficial da nossa equipe!",
        source: 'predefined',
      },
      {
        title: "DJ Oficial da Viagem",
        description: "Escolha a trilha sonora da próxima viagem de carro e seja o DJ oficial da aventura!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 150,
        justification: "Gratificação de 1-2 dias. Um prêmio divertido que dá poder de escolha.",
        tip: "Com as estrelas de um dia e meio de missões, você comanda a música na próxima viagem!",
        source: 'predefined',
      },
      {
        title: "Escolher usar uma roupa especial",
        description: "Transforme um dia comum em um dia mágico! Use sua fantasia de herói ou aquela roupa de festa que você adora.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 150,
        justification: "Gratificação de 1-2 dias. Um prêmio divertido e de baixo custo.",
        tip: "Com as estrelas de um dia e meio de missões, qualquer dia pode virar um dia de fantasia!",
        source: 'predefined',
      },
      {
        title: "30 Minutos Extras de Tela",
        description: "Desbloqueie um portal mágico para mais 30 minutos de diversão nos seus jogos e vídeos favoritos!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 200,
        justification: "Gratificação de 2 dias. Um valor justo para um privilégio muito desejado.",
        tip: "Que tal um poder extra? Complete suas missões por 2 dias inteirinhos e essa mágica é sua!",
        source: 'predefined',
      },
      {
        title: "Chef da Noite Auxiliar",
        description: "Coloque o chapéu de mestre-cuca e ajude a decidir e a preparar o jantar da família!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 250,
        justification: "Gratificação de 2-3 dias. Incentiva a participação e o aprendizado na cozinha.",
        tip: "Com as estrelas de 2 ou 3 dias de missões, você ganha o poder de ser o chef da noite!",
        source: 'predefined',
      },
      {
        title: "Escolher o filme da família",
        description: "Pegue o controle remoto mágico! Hoje, o mestre do cinema é você e a escolha do filme é toda sua.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 250,
        justification: "Gratificação de 2-3 dias. Um prêmio rápido que dá autonomia.",
        tip: "Com as estrelas de 2 ou 3 dias de missões, o controle remoto da noite de cinema é seu!",
        source: 'predefined',
      },
      {
        title: "Dormir 30 Minutos Mais Tarde",
        description: "Estique um pouquinho a noite para uma brincadeira extra ou para terminar aquele capítulo do seu livro.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 300,
        justification: "Conquista de 3 dias. Um privilégio de alto valor, alinhado com o esforço.",
        tip: "Para esticar a noite, basta ser um herói por 3 dias de missões completas. A noite ficará mais divertida!",
        source: 'predefined',
      },
      {
        title: "1 hora extra de tela",
        description: "Desbloqueie um portal mágico para mais uma hora inteira de diversão nos seus jogos e vídeos favoritos!",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 400,
        justification: "Meta de 4 dias. Um privilégio de altíssimo valor e, por isso, mais desafiador.",
        tip: "Para conquistar 1 hora extra de pura diversão, você precisa mostrar seu foco por 4 dias de missões!",
        source: 'predefined',
      },
      {
        title: "Planejar Café da Manhã Especial",
        description: "Seja o mestre do café da manhã! Você escolhe o cardápio especial para o fim de semana.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 400,
        justification: "Meta de 4 dias. Um prêmio que envolve planejamento e criatividade.",
        tip: "Com o esforço de 4 dias de missões, você se torna o chef oficial do café da manhã especial!",
        source: 'predefined',
      },
      {
        title: "Café da manhã na cama",
        description: "Um mimo especial para começar o dia como um rei/rainha, com um lanche servido no seu quarto!",
        userCategory: "Privilégios",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 450,
        justification: "Conquista de 4 dias. Valorizado para ser um evento especial e memorável.",
        tip: "Em 4 dias de missões completas, você conquista um café da manhã de realeza no seu quarto!",
        source: 'predefined',
      },
      {
        title: "Vale-Pular-Tarefa",
        description: "Um passe livre mágico! Use este poder para pular uma missão do dia e ter um descanso merecido.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 500,
        justification: "Conquista de 4-5 dias. Um prêmio valioso, mas não tão fácil de obter.",
        tip: "Acumule as estrelas de quase 1 semana de missões e ganhe um passe livre mágico!",
        source: 'predefined',
      },
      {
        title: "Encontro exclusivo 1-para-1",
        description: "Uma aventura super especial, só você e um guardião! Um tempo só nosso para fazer o que você mais gosta.",
        userCategory: "Privilégios",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 700,
        justification: "Meta semanal. Valorizado para refletir um momento especial e exclusivo.",
        tip: "Uma semana inteira de aventuras garante um passeio super especial só nosso!",
        source: 'predefined',
      },
      {
        title: "Decidir Atividade do Fim de Semana",
        description: "Planejar a principal diversão da família.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 700,
        justification: "Meta semanal. Recompensa que exige o esforço consistente de uma semana.",
        tip: "Conclua 1 semana de missões e você se torna o Planejador Oficial de Aventuras do fim de semana!",
        source: 'predefined',
      },
      {
        title: "O Dia do Sim (com Regras)",
        description: "Um dia inteiro onde o poder da escolha é seu! Você decide as brincadeiras e os lanches.",
        userCategory: "Privilégios",
        suggestedAppCategory: "privileges",
        isMaterialSuggestion: false,
        starsCost: 8500,
        justification: "\"Sonho\" de longo prazo. Uma recompensa épica que exige ~3 meses de esforço.",
        tip: "Este é um prêmio lendário! Continue sua jornada por uns 3 meses. Nesse dia, o poder da escolha será todo seu!",
        source: 'predefined',
      },
    ],
  },
  {
      userCategory: "Guloseimas Mágicas (Pequenas Conquistas)",
      description: "Recompensas rápidas e saborosas para celebrar as conquistas do dia a dia.",
      icon: CakeSlice,
      items: [
        {
            title: "Picolé no fim do dia",
            description: "Um prêmio refrescante para celebrar um dia de missões bem feitas.",
            userCategory: "Guloseimas Mágicas (Pequenas Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: true,
            starsCost: 150,
            justification: "Gratificação de 1-2 dias. Uma recompensa simples para um dia de esforço.",
            tip: "Com as estrelas de um dia e meio de esforço, você conquista um picolé para refrescar o fim da tarde!",
            source: 'predefined',
        },
        {
            title: "Sorvete de sobremesa",
            description: "Transforme uma sobremesa comum em uma festa gelada e deliciosa!",
            userCategory: "Guloseimas Mágicas (Pequenas Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: true,
            starsCost: 200,
            justification: "Gratificação de 2 dias. Um prêmio rápido e muito desejado.",
            tip: "Com as estrelas de dois dias de missões, você pode deixar a sobremesa ainda mais gostosa e geladinha!",
            source: 'predefined',
        },
        {
            title: "Açaí no fim do dia",
            description: "Uma tigela de super-energia para recarregar os poderes depois de um dia de aventuras.",
            userCategory: "Guloseimas Mágicas (Pequenas Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: true,
            starsCost: 250,
            justification: "Gratificação de 2-3 dias. Um lanche especial que vale um esforço extra.",
            tip: "Com as estrelas de dois ou três dias de missões, você ganha uma tigela de açaí cheia de poder!",
            source: 'predefined',
        },
      ]
  },
   {
      userCategory: "Refeições de Aventura (Médias Conquistas)",
      description: "Recompensas que transformam refeições em eventos especiais.",
      icon: Utensils,
      items: [
        {
            title: "Trocar a janta por lanche em casa",
            description: "Que tal uma noite diferente? Troque o jantar por um lanche divertido escolhido por você!",
            userCategory: "Refeições de Aventura (Médias Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 400,
            justification: "Meta de 4 dias. Um privilégio especial que muda a rotina da noite.",
            tip: "Com as estrelas de quatro dias de missões, você vira o chef e transforma o jantar em uma noite do lanche!",
            source: 'predefined',
        },
        {
            title: "Lanchar na rua (fast food)",
            description: "Uma aventura gastronômica no seu restaurante de lanches favorito!",
            userCategory: "Refeições de Aventura (Médias Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 700,
            justification: "Meta semanal. Uma recompensa clássica que exige o esforço de uma semana.",
            tip: "Uma semana de missões perfeitas e você conquista um lanche de campeão no seu lugar favorito!",
            source: 'predefined',
        },
        {
            title: "Almoçar/Jantar no restaurante",
            description: "Um passeio especial para experimentar comidas diferentes em um restaurante escolhido pela família.",
            userCategory: "Refeições de Aventura (Médias Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 2000,
            justification: "Meta de ~3 semanas. Uma experiência familiar mais completa.",
            tip: "Junte estrelas por umas 3 semanas e você ganha o poder de levar toda a equipe para um almoço ou jantar especial!",
            source: 'predefined',
        },
      ]
  },
  {
      userCategory: "Passeios de Herói (Grandes Conquistas)",
      description: "Recompensas que envolvem passeios e atividades fora de casa.",
      icon: FerrisWheel,
      items: [
        {
            title: "Banho de mangueira",
            description: "Uma tarde de muita risada e diversão se refrescando com um banho de mangueira no quintal!",
            userCategory: "Passeios de Herói (Grandes Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 300,
            justification: "Conquista de 3 dias. Uma recompensa simples e super divertida para um dia de calor.",
            tip: "Com o esforço de três dias de missões, você libera uma aventura aquática super refrescante!",
            source: 'predefined',
        },
        {
            title: "Banho de piscina",
            description: "Um dia inteiro de mergulhos e brincadeiras na piscina!",
            userCategory: "Passeios de Herói (Grandes Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 700,
            justification: "Meta semanal. Uma recompensa de alto valor para um fim de semana perfeito.",
            tip: "Uma semana inteira de dedicação nas missões vale um dia inteiro de mergulhos e diversão na piscina!",
            source: 'predefined',
        },
        {
            title: "Churrasco em casa",
            description: "Um dia de celebração em família, com comida gostosa e muita brincadeira ao ar livre.",
            userCategory: "Passeios de Herói (Grandes Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 1000,
            justification: "Meta de 1-2 semanas. Uma recompensa que envolve toda a família.",
            tip: "Com as estrelas de uma semana e meia de esforço, você convoca um dia de festa para a equipe toda!",
            source: 'predefined',
        },
        {
            title: "Ir à praia",
            description: "Um dia de castelos de areia, mergulhos no mar e muita diversão sob o sol!",
            userCategory: "Passeios de Herói (Grandes Conquistas)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 2500,
            justification: "Meta mensal. Um passeio completo que exige planejamento.",
            tip: "Junte estrelas por quase um mês e podemos trocar as missões pela areia e pelo mar em um dia de praia!",
            source: 'predefined',
        },
      ]
  },
  {
      userCategory: "Jornadas Lendárias (Sonhos)",
      description: "As maiores recompensas, para os maiores sonhos!",
      icon: Plane,
      items: [
        {
            title: "Viagem curta",
            description: "Preparar as malas para uma aventura inesquecível! Uma viagem de fim de semana para um lugar novo e divertido.",
            userCategory: "Jornadas Lendárias (Sonhos)",
            suggestedAppCategory: "experiences",
            isMaterialSuggestion: false,
            starsCost: 9000,
            justification: "\"Sonho\" de ~3 meses. A recompensa máxima, que exige consistência e dedicação.",
            tip: "Esta é uma jornada lendária! Continue sua aventura por uns 3 meses e prepararemos as malas para um lugar incrível!",
            source: 'predefined',
        },
      ]
  },
  {
    userCategory: "Experiências",
    description: "O foco aqui é criar memórias afetivas e fortalecer laços, que são as recompensas mais duradouras e alinhadas ao propósito do MiniHeróis de conectar a família.",
    icon: PartyPopper,
    items: [
      {
        title: "Sessão de fotos temáticas",
        description: "Hora de virar modelo! Uma sessão de fotos divertida em casa, com fantasias e muitas poses.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 300,
        justification: "Conquista de 3 dias. Uma atividade criativa e que gera memórias.",
        tip: "Com as estrelas de 3 dias de missões, preparamos um estúdio fotográfico só para você!",
        source: 'predefined',
      },
      {
        title: "Noite de Karaokê em família",
        description: "Pegue o microfone e solte a voz! Uma noite para se transformar na estrela da música.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 400,
        justification: "Meta de 4 dias. Uma atividade divertida que envolve toda a família.",
        tip: "Quatro dias de dedicação e você se torna a estrela do nosso palco particular!",
        source: 'predefined',
      },
      {
        title: "Acampamento na sala",
        description: "Transforme a sala em uma floresta mágica! Uma noite com cabana de lençóis e lanternas.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 600,
        justification: "Conquista semanal. Um evento especial de fim de semana.",
        tip: "Uma semana de missões bem feitas e você ganha uma noite mágica de acampamento dentro de casa!",
        source: 'predefined',
      },
      {
        title: "Piquenique temático",
        description: "Uma aventura com lanches gostosos ao ar livre! Você ajuda a escolher o tema.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 1000,
        justification: "Meta de 1-2 semanas. Exige um pouco mais de planejamento e esforço.",
        tip: "Com as estrelas de 1 semana e meia de esforço, podemos criar uma aventura ao ar livre!",
        source: 'predefined',
      },
      {
        title: "Levar amigo para passeio",
        description: "Compartilhe a diversão! Convide um amigo especial para um passeio divertido com a família.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 2000,
        justification: "Meta de ~3 semanas. Uma recompensa social de grande valor para a criança.",
        tip: "Junte estrelas por umas 3 semanas e você poderá levar seu melhor amigo para uma aventura!",
        source: 'predefined',
      },
      {
        title: "Estreia no cinema",
        description: "Pipoca, tela gigante e a magia do cinema! Vamos assistir àquele filme incrível que acabou de ser lançado.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 1500,
        justification: "Meta quinzenal. Uma recompensa mais significativa.",
        tip: "Duas semanas de foco total nas missões te levam para a telona do cinema!",
        source: 'predefined',
      },
      {
        title: "Peça de teatro infantil",
        description: "Uma tarde cultural e divertida, com histórias e personagens que saltam do palco.",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 2000,
        justification: "Meta de ~3 semanas. Ajustado para o valor de uma experiência cultural externa.",
        tip: "Junte as estrelas de três semanas de esforço e você garante seu ingresso para um mundo de imaginação!",
        source: 'predefined',
      },
      {
        title: "Festa do pijama com amigos",
        description: "Uma noite cheia de diversão, jogos e segredos com seus melhores amigos em casa!",
        userCategory: "Experiências",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 5000,
        justification: "\"Sonho\" de ~2 meses. Um grande evento que exige planejamento.",
        tip: "Esta é uma grande meta! Continue sua jornada por quase 2 meses e prepare-se para a melhor festa do pijama!",
        source: 'predefined',
      },
    ],
  },
  {
    userCategory: "Itens Materiais (com Ressalvas)",
    description: "Recompensas tangíveis, mas sempre conectadas a um propósito, como um hobby ou o desenvolvimento de uma habilidade, para evitar o consumismo puro. Lembre-se de evitar condicionar itens essenciais.",
    icon: ShoppingBag,
    items: [
      {
        title: "Adesivos decorativos",
        description: "Decore seu caderno ou seu quarto com adesivos incríveis dos seus personagens favoritos!",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 100,
        justification: "Conquista de 1 dia. Um item de baixo custo para personalização.",
        tip: "Com as missões de hoje, você já pode escolher adesivos novos para enfeitar suas coisas!",
        source: 'predefined',
      },
      {
        title: "Pacote de figurinhas",
        description: "Descubra novos heróis e complete seu álbum com um pacote de figurinhas novinho!",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 100,
        justification: "Conquista de 1 dia. Uma recompensa muito rápida e de baixo valor.",
        tip: "É super rápido! Complete as missões de hoje e um pacote de figurinhas já pode ser seu!",
        source: 'predefined',
      },
      {
        title: "Massinha de modelar nova cor",
        description: "Uma nova cor para expandir seu universo de criações e esculturas de massinha!",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 100,
        justification: "Conquista de 1 dia. Um item criativo e de baixo custo.",
        tip: "Com as missões de hoje, você já pode adicionar uma nova cor mágica ao seu kit de massinha!",
        source: 'predefined',
      },
      {
        title: "Gibi ou revista em quadrinhos",
        description: "Uma nova aventura cheia de ação e desenhos espera por você. Qual será a história de hoje?",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 200,
        justification: "Gratificação de 2 dias. Alinhado com o custo de um item de leitura rápida.",
        tip: "Dois dias de esforço e uma nova história em quadrinhos é sua!",
        source: 'predefined',
      },
      {
        title: "Partitura nova",
        description: "Para o músico da casa! Desbloqueie a partitura daquela música que você está louco para aprender.",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 300,
        justification: "Conquista de 3 dias. Um item específico para o desenvolvimento de um hobby.",
        tip: "Com as estrelas de 3 dias de missões, você pode desbloquear a próxima música da sua jornada!",
        source: 'predefined',
      },
      {
        title: "Livro novo escolhido",
        description: "Escolha o próximo mundo mágico que você quer explorar! Qual será sua nova aventura literária?",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 700,
        justification: "Meta semanal. Incentiva a leitura e exige o esforço de uma semana.",
        tip: "Uma semana perfeita de missões te dá o poder de escolher sua próxima grande aventura literária!",
        source: 'predefined',
      },
      {
        title: "Kit de arte específico",
        description: "Libere sua criatividade com novas cores e materiais! Um kit especial para suas obras de arte.",
        userCategory: "Itens Materiais (com Ressalvas)",
        suggestedAppCategory: "material_items",
        isMaterialSuggestion: true,
        starsCost: 1000,
        justification: "Meta de 1-2 semanas. Custo ajustado para um item de desenvolvimento de hobby.",
        tip: "Com 1 semana e meia de missões, você pode desbloquear novas ferramentas para sua criatividade!",
        source: 'predefined',
      },
    ],
  },
  {
    userCategory: "Desenvolvimento Pessoal",
    description: "Recompensas que incentivam diretamente o aprendizado e a exploração de novos talentos, alinhadas à Teoria das Múltiplas Inteligências.",
    icon: GraduationCap,
    items: [
       {
        title: "Diário ou caderno de desenho",
        description: "Um lugar secreto e especial para guardar suas ideias, sonhos e os desenhos mais incríveis!",
        userCategory: "Desenvolvimento Pessoal",
        suggestedAppCategory: "personal_development",
        isMaterialSuggestion: true,
        starsCost: 400,
        justification: "Meta de 4 dias. Uma ferramenta importante de autoexpressão.",
        tip: "Para guardar suas ideias secretas, complete suas missões por 4 dias. Um diário novinho estará te esperando!",
        source: 'predefined',
      },
      {
        title: "App ou jogo educativo premium",
        description: "Desbloqueie um novo jogo ou aplicativo super divertido que também te ensina coisas novas!",
        userCategory: "Desenvolvimento Pessoal",
        suggestedAppCategory: "personal_development",
        isMaterialSuggestion: false,
        starsCost: 1200,
        justification: "Meta quinzenal. Alinhado com o custo de um software ou assinatura.",
        tip: "Com o esforço de 2 semanas, você pode desbloquear um novo mundo de aprendizado e diversão!",
        source: 'predefined',
      },
      {
        title: "Kit Faça Você Mesmo (DIY)",
        description: "Torne-se um inventor! Um kit com tudo o que você precisa para construir um projeto incrível.",
        userCategory: "Desenvolvimento Pessoal",
        suggestedAppCategory: "personal_development",
        isMaterialSuggestion: true,
        starsCost: 900,
        justification: "Meta de 1-2 semanas. Uma atividade educativa e prática.",
        tip: "Uma semana e meia de dedicação e você pode se tornar um mestre construtor!",
        source: 'predefined',
      },
      {
        title: "Dia em parque de aventuras",
        description: "Um dia de pura adrenalina e diversão em um parque com brinquedos e desafios emocionantes!",
        userCategory: "Desenvolvimento Pessoal",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 6000,
        justification: "\"Sonho\" de ~2 meses. Uma grande recompensa que exige planejamento.",
        tip: "Este é um sonho de aventura! Junte suas estrelas por cerca de 2 meses e prepare-se para um dia inesquecível!",
        source: 'predefined',
      },
      {
        title: "Aula experimental",
        description: "Que tal experimentar um novo superpoder? Uma aula de algo que você sempre quis aprender!",
        userCategory: "Desenvolvimento Pessoal",
        suggestedAppCategory: "experiences",
        isMaterialSuggestion: false,
        starsCost: 1500,
        justification: "Meta quinzenal. Incentiva a descoberta de novos hobbies e talentos.",
        tip: "Junte estrelas por 2 semanas e você poderá experimentar uma aula nova e descobrir um novo talento!",
        source: 'predefined',
      },
    ],
  },
  {
    userCategory: "Impacto e Generosidade",
    description: "Recompensas que ensinam sobre empatia, cidadania e o prazer de ajudar, transformando o Mini Herói em um herói também para o mundo.",
    icon: HeartHandshake,
    items: [
      {
        title: "Ajudar em abrigo de animais",
        description: "Use seu superpoder de carinho para ajudar a cuidar de cães e gatos que precisam de amor.",
        userCategory: "Impacto e Generosidade",
        suggestedAppCategory: "impact_generosity",
        isMaterialSuggestion: false,
        starsCost: 50,
        justification: "Ato de altruísmo. Custo simbólico para incentivar o voluntariado.",
        tip: "As estrelas de algumas poucas missões podem se transformar em muito carinho para um animalzinho!",
        source: 'predefined',
      },
      {
        title: "Desenho/cartão para vizinho",
        description: "Crie uma obra de arte especial para presentear um vizinho e espalhar alegria pelo bairro!",
        userCategory: "Impacto e Generosidade",
        suggestedAppCategory: "impact_generosity",
        isMaterialSuggestion: false,
        starsCost: 50,
        justification: "Ato de gentileza. Custo simbólico para reforçar pequenos gestos.",
        tip: "Suas estrelas de só algumas missões podem virar um grande sorriso no rosto de alguém!",
        source: 'predefined',
      },
      {
        title: "Doar brinquedo/livro novo",
        description: "Use seu coração de herói para escolher um presente especial e levar alegria para outra criança!",
        userCategory: "Impacto e Generosidade",
        suggestedAppCategory: "impact_generosity",
        isMaterialSuggestion: false,
        starsCost: 100,
        justification: "Conquista diária. O custo baixo incentiva a generosidade.",
        tip: "Com o esforço das missões de 1 dia, você ganha o superpoder de fazer outra criança muito feliz!",
        source: 'predefined',
      },
      {
        title: "Preparar lanches para doar",
        description: "Use seus talentos de chef para preparar lanches gostosos e doar para quem precisa.",
        userCategory: "Impacto e Generosidade",
        suggestedAppCategory: "impact_generosity",
        isMaterialSuggestion: false,
        starsCost: 150,
        justification: "Ato de generosidade. Um pouco mais de esforço, com grande impacto.",
        tip: "Com as estrelas de um dia e meio, sua ajuda na cozinha pode alimentar e alegrar o dia de alguém!",
        source: 'predefined',
      },
    ],
  },
];
